spring:
  application:
  name: warehouse
  datasource:
    url: jdbc:mysql://localhost:3306/school_warehouse?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 7695

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
      show-sql: false
      open-in-view: false

server:
  port: 8080

app:
  jwt:
    secret: school-warehouse-secret-key-min-32-chars-long
    expiration-ms: 86400000